# -*- coding: utf-8 -*-
"""CD 完整部署采样验证与 online/EMA 部署权重选择常量。"""

from diffusion_consistency_radar.deployment_validation import (
    CD_DEPLOYMENT_VALIDATION_SELECTOR,
    DEPLOYMENT_VALIDATION_PROTOCOL,
    DEPLOYMENT_VALIDATION_SPLIT,
)


CD_VALIDATION_PROTOCOL = DEPLOYMENT_VALIDATION_PROTOCOL
CD_VALIDATION_SELECTOR = CD_DEPLOYMENT_VALIDATION_SELECTOR
CD_VALIDATION_SPLIT = DEPLOYMENT_VALIDATION_SPLIT
CD_DENOISING_DIAGNOSTIC_PROTOCOL = "cd_target_latent_denoising_diagnostic_v1"
